apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  name: issuer-node-vault-deployment
  labels:
    app: issuer-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: issuer-node-vault
  template:
    metadata:
      labels:
        app: issuer-node-vault # Label for the pod and will be used in the service
    spec:
      containers:
        - name: vault
          securityContext: 
            capabilities:
              add:
                - IPC_LOCK
          image: vault:1.13.2
          imagePullPolicy: "IfNotPresent"
          env:
            - name: VAULT_ADDR
              value: http://127.0.0.1:8200
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: private-key-secret
                  key: private-key

            - name: VAULT_PWD
              valueFrom:
                secretKeyRef:
                  name: private-key-secret
                  key: vault-pwd
          ports:
            - containerPort: 8200
          command: ["sh", "-c", "/vault/config/init.sh"]

          volumeMounts:
          - mountPath: /vault/plugins
            name: vault-volume
          - mountPath: /vault/data
            name: vault-volume
          - mountPath: /vault/file
            name: vault-volume
          - mountPath: /vault/config
            name: vault-config  

      volumes:
      - name: vault-volume
        persistentVolumeClaim:
            claimName: issuer-node-vault-pvc

      - name: vault-config
        configMap:
          name: issuer-node-vault-configmap
          defaultMode: 0500
          items:
          - key: vault.json
            path: vault.json
          - key: init.sh
            path: init.sh
          - key: policies.hcl
            path: policies.hcl