apiVersion: v1
kind: PersistentVolume
metadata:
  name: issuer-node-vault-pv
  labels:
    app: issuer-node
spec:
  storageClassName: manual
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume_4"


---

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: issuer-node-vault-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi