FROM golang:1.22 AS base
ARG VERSION

WORKDIR /service
ENV GOBIN /service/bin

COPY go.mod .
COPY go.sum .
COPY ./cmd/kms_priv_key_importer/ ./cmd/kms_priv_key_importer/
COPY ./internal/config ./internal/config
COPY ./internal/kms ./internal/kms
COPY ./internal/log ./internal/log
COPY ./internal/providers ./internal/providers
COPY ./internal/common ./internal/common
COPY ./pkg/PKCS8DER ./pkg/PKCS8DER


RUN go install -buildvcs=false -ldflags "-X main.build=${VERSION}" ./cmd/kms_priv_key_importer/main.go

FROM alpine:latest
RUN apk add --no-cache libstdc++ gcompat libgomp
RUN apk add --update busybox>1.3.1-r0
RUN apk add --update openssl>3.1.4-r1
RUN ln -sfv ld-linux-x86-64.so.2 /lib/libresolv.so.2
RUN apk add --no-cache aws-cli


RUN apk add doas; \
    adduser -S issuer -D -G wheel; \
    echo 'permit nopass :wheel as root' >> /etc/doas.d/doas.conf;
RUN chmod g+rx,o+rx /

COPY --from=base ./service/bin/main /usr/local/bin/kms_priv_key_importer
RUN chmod +x /usr/local/bin/kms_priv_key_importer