# This patch file is used to override the default values in the issuer-node-api-configmap.yaml file.

# ISSUER_ETHEREUM_URL is the URL of the Ethereum node that the issuer-node-api will connect to.
- op: replace
  path: /data/ISSUER_ETHEREUM_URL
  value: "https://polygon-mumbai.g.alchemy.com/v2/xaP2_t9EUM2VYDgCgMI0k9KqDyJPvZ89"

# ISSUER_SERVER_URL is the URL of the issuer-node-api.
- op: replace
  path: /data/ISSUER_SERVER_URL
  value: "http://issuer-node-api.info"


# Add more issuer-node-api configuration here.

# --- ------------------------------- ---
# --- This values must not be changed ---
# --- ------------------------------- ---
- op: replace
  path: /data/ISSUER_ETHEREUM_RESOLVER_PREFIX
  value: "polygon:mumbai"

- op: replace
  path: /data/ISSUER_ETHEREUM_CONTRACT_ADDRESS
  value: "0x134B1BE34911E39A8397ec6289782989729807a4"