apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingressroute
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      # match: Host(`core-api-issuer-node-k8s.privado.id`) && PathPrefix(`/main`)
      match: Host(`{{ .Values.apidomain }}`) && PathPrefix(`/{{ .Release.Namespace }}`)
      middlewares:
        - name: rewritebackend
          namespace: {{ .Release.Namespace }}
      services:
        - name: api-issuer-node-svc
          port: 3001
          namespace: {{ .Release.Namespace }}
    - kind: Rule
      # match: Host(`issuer-node-k8s.privado.id`) && PathPrefix(`/main`)
      match: Host(`{{ .Values.uidomain }}`) && PathPrefix(`/{{ .Release.Namespace }}`)
      middlewares:
        - name: rewritebackend
          namespace: {{ .Release.Namespace }}
      services:
        - name: ui-issuer-node-svc
          port: 8080
          namespace: {{ .Release.Namespace }}
  tls:
    secretName: wildcard-privado-id-prod-tls