---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: privado-id
  namespace: issuer-node # Must be in the same namespace than ingress
spec:
  secretName: wildcard-privado-id-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.privado.id"
  dnsNames:
  - "*.privado.id"