apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: {{ .Values.postgresIssuerNode.pvc.postgres }}
  labels:
  {{- include "privadoid-issuer.postgresIssuerNode.common.labels" . | nindent 4 }} 
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresIssuerNode.pvc.storageRequest }}