apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresIssuerNode.service.name }}
  labels: 
    {{- include "privadoid-issuer.postgresIssuerNode.staticLabel" . | nindent 4 }}
    {{- include "privadoid-issuer.postgresIssuerNode.common.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "privadoid-issuer.postgresIssuerNode.Labels" . | nindent 4 }}
    {{- include "privadoid-issuer.postgresIssuerNode.selectorLabels" . | nindent 4 }}
  {{- with .Values.postgresIssuerNode.service.ports }}
  ports: 
    {{-  toYaml . | nindent 2 }}
  {{- end }}