openapi: 3.1.0
info:
  title: Self Hosted ID Platform
  description: |
    Documentation for the Self Hosted ID Admin Platform
  version: 0.1.0

servers:
  - description: Local
    url: http://localhost:3002

tags:
  - name: Identity
    description: Collection of endpoints related to Identity
  - name: Claim
    description: Collection of endpoints related to Claims
  - name: Agent
    description: Collection of endpoints related to Mobile

paths:
  /:
    get:
      summary: Get the documentation
      operationId: GetDocumentation
      x-internal: true
      responses:
        200:
          description: success and returns the documentation in HTML format

  /static/docs/api_admin/api.yaml:
    get:
      summary: Get the documentation yaml file
      operationId: GetYaml
      x-internal: true
      responses:
        200:
          description: success and returns the documentation in Yaml format

  /status:
    get:
      summary: Healthcheck
      operationId: Health
      responses:
        '200':
          description: All services are running
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
        '500':
          $ref: '#/components/responses/500'

  /v1/authentication/qrcode:
    get:
      summary: get authentication qrcode
      operationId: authQRCode
      description: Authentication qrcode
      tags:
        - auth
      responses:
        '200':
          description: authentication qrcode
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationQrCodeResponse'
        '500':
          $ref: '#/components/responses/500'

  /v1/authentication/callback:
    post:
      summary: authentication callback
      operationId: authCallback
      description: Authentication callback
      tags:
        - auth
      parameters:
        - $ref: '#/components/parameters/sessionID'
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: jwz-token
      responses:
        '200':
          description: ok
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'

  /say-hi:
    get:
      summary: Say Hi endpoint
      operationId: SayHi
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: Say hi endpoint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SayHi'
        '500':
          $ref: '#/components/responses/500'


components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:
    Health:
      type: object
      x-omitempty: false
      additionalProperties:
        type: boolean

    SayHi:
      type: object
      required:
        - message
      x-omitempty: false
      properties:
        message:
          type: string
          example: 'Hi!'

    AuthenticationQrCodeResponse:
      type: object
      required:
        - id
        - typ
        - type
        - thid
        - body
        - from
      properties:
        id:
          type: string
        typ:
          type: string
        type:
          type: string
        thid:
          type: string
        body:
          type: object
          required:
            - callbackUrl
            - reason
            - scope
          properties:
            callbackUrl:
              type: string
            reason:
              type: string
            scope:
              type: array
        from:
          type: string

    GenericErrorMessage:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: 'Something happen'

  parameters:
    sessionID:
      name: sessionID
      in: query
      description: Session ID
      schema:
        type: string

  responses:
    '400':
      description: 'Bad Request'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericErrorMessage'
    '500':
      description: 'Internal Server error'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericErrorMessage'
