# This patch file is used to override the default values in the issuer-node-api-configmap.yaml file.

# ISSUER_ETHEREUM_URL is the URL of the Ethereum node that the issuer-node-api will connect to.
- op: replace
  path: /data/ISSUER_ETHEREUM_URL
  value: "https://polygon-mainnet.g.alchemy.com/v2/X2HI8cErI_6RYdUVS0SvSfCZCYDCSrzt"

# ISSUER_SERVER_URL is the URL of the issuer-node-api.
- op: replace
  path: /data/ISSUER_SERVER_URL
  value: "http://issuer-node-api.mainnet.info"


# Add more issuer-node-api configuration here.

# --- ------------------------------- ---
# --- This values must not be changed ---
# --- ------------------------------- ---
- op: replace
  path: /data/ISSUER_ETHEREUM_RESOLVER_PREFIX
  value: "polygon:main"

- op: replace
  path: /data/ISSUER_ETHEREUM_CONTRACT_ADDRESS
  value: "0x624ce98D2d27b20b8f8d521723Df8fC4db71D79D"