redisIssuerNode:
  labels:
    app: issuer-node
  deployment:
    replicaCount: 1
    name: redis-issuer-node
    image:
      repository: redis
      tag: 'alpine'
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "0.5"
        memory: 1Gi  
    labels: 
      app: redis-issuer-node
    containerPort: 6379
    containerName: redis
  service:
    name: redis-issuer-node-svc
    ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
    selector: redis-issuer-node