
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redisIssuerNode.deployment.name }}
  labels:
  {{- include "privadoid-issuer.redisIssuerNode.common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redisIssuerNode.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "privadoid-issuer.redisIssuerNode.Labels" . | nindent 6 }}
      {{- include "privadoid-issuer.redisIssuerNode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "privadoid-issuer.redisIssuerNode.Labels" . | nindent 8 }}
        {{- include "privadoid-issuer.redisIssuerNode.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "helpers.serviceAccountName" . }}
      containers:
      - name: {{ .Values.redisIssuerNode.deployment.containerName }}
        image: {{ .Values.redisIssuerNode.deployment.image.repository }}:{{ .Values.redisIssuerNode.deployment.image.tag }}
        ports:
          - containerPort: {{ .Values.redisIssuerNode.deployment.containerPort }}
        resources: {{- toYaml .Values.redisIssuerNode.deployment.resources | nindent 10 }}