apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.vaultIssuerNode.configMap.vaultConfigName }}
  labels:
    {{ include "privadoid-issuer.vaultIssuerNode.staticLabel" . }}
    {{- include "privadoid-issuer.vaultIssuerNode.common.labels" . | nindent 4 }}
data:
  vault.json: {{- .Values.vaultIssuerNode.configMap.vaultJson | toYaml | indent 4 }}    
  init.sh: {{ tpl .Values.vaultIssuerNode.configMap.initSh . | toYaml | indent 4}}
  policies.hcl: {{-  .Values.vaultIssuerNode.configMap.policieshcl | toYaml | indent 4 }}
  