apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: {{ .Values.vaultIssuerNode.pvc.vault }}
  labels:
  {{- include "privadoid-issuer.vaultIssuerNode.common.labels" . | nindent 4 }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.vaultIssuerNode.pvc.storageRequest }}
