apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vaultIssuerNode.service.name }}
  labels: 
    {{ include "privadoid-issuer.vaultIssuerNode.staticLabel" . }}
    {{- include "privadoid-issuer.vaultIssuerNode.common.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "privadoid-issuer.vaultIssuerNode.Labels" . | nindent 4 }}
    {{- include "privadoid-issuer.vaultIssuerNode.selectorLabels" . | nindent 4 }}
  {{- with .Values.vaultIssuerNode.service.ports }}
  ports: 
    {{-  toYaml . | nindent 2 }}
  {{- end }}