apiVersion: v2
name: privadoid-issuer
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: vault
    version: 0.1.0
    repository: "file://charts/vault"
  - name: postgres
    version: 0.1.0
    repository: "file://charts/postgres"
  - name: redis
    version: 0.1.0
    repository: "file://charts/redis"
  - name: ingress
    version: 0.1.0
    repository: "file://charts/ingress"
