apiVersion: v1
kind: ConfigMap
metadata:
  name: issuer-node-ui-configmap
  labels:
    app: issuer-node
data:
  # This is the URL of the issuer-node-api-ui service
  ISSUER_API_UI_SERVER_URL: http://issuer-node.info
  ISSUER_UI_AUTH_USERNAME: user-ui
  ISSUER_UI_AUTH_PASSWORD: password-ui
  ISSUER_UI_BLOCK_EXPLORER_URL: https://mumbai.polygonscan.com
  ISSUER_API_UI_AUTH_USER: user-api
  ISSUER_API_UI_AUTH_PASSWORD: password-api
  ISSUER_API_UI_ISSUER_NAME: my issuer k8s
  ISSUER_UI_IPFS_GATEWAY_URL: https://ipfs.io