apiVersion: v1
kind: PersistentVolume
metadata:
  name: issuer-node-pv 
  labels:
    app: issuer-node
spec:
  storageClassName: manual
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume_05"
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: issuer-node-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi