



.PHONY: expose-api-service
expose-api-service:
	@echo "Exposing API service..."
	minikube service --url api-issuer-node-svc

.PHONY: expose-api-ui-service
expose-api-ui-service:
	@echo "Exposing API UI service..."
	minikube service --url api-ui-issuer-node-svc

.PHONY: expose-ui-service
expose-ui-service:
	@echo "Exposing UI service..."
	minikube service --url ui-issuer-node-svc

