apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-issuer-node-pv 
  labels:
    app: issuer-node
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume_01"


---

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: postgresql-issuer-node-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi