apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgresIssuerNode.configMap.postgresName }}
  labels:
    {{- include "polygon-id-issuer.staticLabel" . | nindent 4 }}
    {{- include "polygon-id-issuer.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgresIssuerNode.configMap.postgresDb }}
  POSTGRES_PASSWORD: {{ .Values.postgresIssuerNode.configMap.postgresPassword }}
  POSTGRES_USER: {{ .Values.postgresIssuerNode.configMap.postgresUser }}
  init.sql: |
    {{ .Values.postgresIssuerNode.configMap.initSql | toYaml  }}