apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresIssuerNode.service.name }}
  labels: 
    {{- include "polygon-id-issuer.staticLabel" . | nindent 4}}
    {{- include "polygon-id-issuer.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "polygon-id-issuer.postgresIssuerNode.Labels" . | nindent 4 }}
    {{- include "polygon-id-issuer.selectorLabels" . | nindent 4 }}
  {{- with .Values.postgresIssuerNode.service.ports }}
  ports: 
    {{-  toYaml . | nindent 2 }}
  {{- end }}