
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redisIssuerNode.deployment.name }} # check if labels need to be added.
  labels:
  {{- include "polygon-id-issuer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redisIssuerNode.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "polygon-id-issuer.redisIssuerNode.Labels" . | nindent 6 }}
      {{- include "polygon-id-issuer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "polygon-id-issuer.redisIssuerNode.Labels" . | nindent 8 }}
        {{- include "polygon-id-issuer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: issuer-node-service-account
      containers:
      - name: {{ .Values.redisIssuerNode.deployment.containerName }}
        image: {{ .Values.redisIssuerNode.deployment.image.repository }}:{{ .Values.redisIssuerNode.deployment.image.tag }}
        ports:
          - containerPort: {{ .Values.redisIssuerNode.deployment.containerPort }}
        resources: {{- toYaml .Values.redisIssuerNode.deployment.resources | nindent 10 }}