apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
  {{- include "polygon-id-issuer.labels" . | nindent 4 }}
data:
  private-key: {{ .Values.privateKey | b64enc | quote }}