name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '00 05 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          exempt-issue-labels: 'bug,enhancement'
          stale-issue-message: 'This issue is stale because it has been open 20 days with no activity. Remove stale label, add the enhancement label or comment to avoid closing it in 10 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 10 days with no activity.'
          days-before-stale: 20
          days-before-close: 10
          days-before-pr-stale: -1
          days-before-pr-close: -1
