name: Build a Push Docker Image to Docker Hub

on:
  workflow_run:
    workflows: ["Checks"]
    branches:  ["develop"]
    types:
      - completed

jobs:
  docker:
    name: Build and deploy image Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get version
        run: echo "::set-output name=VERSION::$(git rev-parse --short HEAD)"
        id: version

      - name: Build and push ui
        uses: docker/build-push-action@v4
        env:
          IMAGE_TAG: ${{ steps.version.outputs.VERSION }}
        with:
          context: ./ui
          platforms: linux/arm64, linux/amd64
          push: true
          tags: 0xpolygon/issuernode-ui:${{ env.IMAGE_TAG }}

      - name: Build and push amd64 and arm64 image
        uses: docker/build-push-action@v4
        env:
          IMAGE_TAG: ${{ steps.version.outputs.VERSION }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 0xpolygon/issuernode:${{ env.IMAGE_TAG }}


