name: Checks

on:
  workflow_call:

jobs:
  # tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: actions/setup-go@v3
  #       with:
  #         go-version-file: go.mod
  #         cache: true

  #     - name: Docker Compose
  #       uses: isbang/compose-action@v1.4.1 # Needs actions/checkout before
  #       with:
  #         compose-file: './infrastructure/local/docker-compose.yml'
  #         services: |
  #            postgres
  #            vault

  #     - run: make tests
  #       env:
  #         POSTGRES_TEST_DATABASE: postgres://postgres:postgres@localhost:5432

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - run: make lint
